"""Public configuration facade for SER."""

from __future__ import annotations

from ser._internal.config.bootstrap import (
    apply_settings,
    get_settings,
    reload_settings,
    resolve_profile_transcription_config,
    settings_override,
)
from ser._internal.config.schema import (
    APP_NAME,
    DEFAULT_FAST_MODEL_FILE_NAME,
    DEFAULT_FAST_SECURE_MODEL_FILE_NAME,
    DEFAULT_FAST_TRAINING_REPORT_FILE_NAME,
    AccurateResearchRuntimeConfig,
    AccurateRuntimeConfig,
    AppConfig,
    ArtifactProfileName,
    AudioReadConfig,
    DataLoaderConfig,
    DatasetConfig,
    FastRuntimeConfig,
    FeatureFlags,
    FeatureRuntimeBackendOverride,
    FeatureRuntimePolicyConfig,
    MediumRuntimeConfig,
    MediumTrainingConfig,
    ModelsConfig,
    NeuralNetConfig,
    ProfileRuntimeConfig,
    QualityGateConfig,
    RuntimeFlags,
    SchemaConfig,
    TimelineConfig,
    TorchRuntimeConfig,
    TrainingConfig,
    TranscriptionConfig,
    WhisperModelConfig,
    default_profile_model_id,
    profile_artifact_file_names,
)
from ser._internal.config.settings_inputs import (
    ResolvedSettingsInputs,
    SettingsInputDeps,
)
from ser.profiles import (
    ProfileCatalogEntry,
    TranscriptionBackendId,
    get_profile_catalog,
)
from ser.utils.torch_inference import normalize_torch_device_selector

__all__ = [
    "APP_NAME",
    "DEFAULT_FAST_MODEL_FILE_NAME",
    "DEFAULT_FAST_SECURE_MODEL_FILE_NAME",
    "DEFAULT_FAST_TRAINING_REPORT_FILE_NAME",
    "AccurateResearchRuntimeConfig",
    "AccurateRuntimeConfig",
    "AppConfig",
    "ArtifactProfileName",
    "AudioReadConfig",
    "DataLoaderConfig",
    "DatasetConfig",
    "FastRuntimeConfig",
    "FeatureFlags",
    "FeatureRuntimeBackendOverride",
    "FeatureRuntimePolicyConfig",
    "MediumRuntimeConfig",
    "MediumTrainingConfig",
    "ModelsConfig",
    "NeuralNetConfig",
    "ProfileCatalogEntry",
    "ProfileRuntimeConfig",
    "QualityGateConfig",
    "ResolvedSettingsInputs",
    "RuntimeFlags",
    "SchemaConfig",
    "SettingsInputDeps",
    "TimelineConfig",
    "TorchRuntimeConfig",
    "TrainingConfig",
    "TranscriptionBackendId",
    "TranscriptionConfig",
    "WhisperModelConfig",
    "apply_settings",
    "default_profile_model_id",
    "get_profile_catalog",
    "get_settings",
    "normalize_torch_device_selector",
    "profile_artifact_file_names",
    "reload_settings",
    "resolve_profile_transcription_config",
    "settings_override",
]
